# Generated by Django 4.2.2 on 2023-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.CharField(max_length=100, verbose_name='рука')),
                ('card_can_play', models.CharField(max_length=100, verbose_name='Активные')),
            ],
        ),
    ]
