# Generated by Django 4.2.2 on 2023-06-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0002_alter_cards_card_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
