# Generated by Django 4.2.2 on 2023-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0004_student_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Count', models.CharField(max_length=20, verbose_name='количество игроков')),
                ('is_reverse', models.BooleanField(default=False, max_length=10)),
                ('how_can_play', models.CharField(max_length=10, verbose_name='ход')),
                ('card_ontable', models.CharField(max_length=10, verbose_name='карта')),
                ('player1', models.CharField(max_length=20, verbose_name='айди игрока 1')),
                ('player2', models.CharField(max_length=20, verbose_name='айди игрока 2')),
                ('player3', models.CharField(max_length=20, verbose_name='айди игрока 3')),
                ('player4', models.CharField(max_length=20, verbose_name='айди игрока 4')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='card_can_play',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='card_list',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='game_id',
            field=models.CharField(default=1, max_length=20, verbose_name='номер игры'),
            preserve_default=False,
        ),
    ]
