# Generated by Django 4.2.2 on 2023-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0005_game_student_card_can_play_student_card_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_ready',
            field=models.BooleanField(default=False, max_length=10, verbose_name='готов'),
        ),
    ]
