# Generated by Django 4.2.2 on 2023-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0006_student_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='card_can_play',
        ),
        migrations.RemoveField(
            model_name='student',
            name='card_list',
        ),
        migrations.AddField(
            model_name='game',
            name='card_can_play1',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_can_play2',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_can_play3',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_can_play4',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_list1',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_list2',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_list3',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='card_list4',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
    ]
