# Generated by Django 4.2.2 on 2023-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0007_remove_student_card_can_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_can_play',
            field=models.CharField(default=1, max_length=100, verbose_name='Активные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='card_list',
            field=models.CharField(default=1, max_length=100, verbose_name='Рука'),
            preserve_default=False,
        ),
    ]
