# Generated by Django 4.2.2 on 2023-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0010_alter_game_is_reverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='flag',
            field=models.BooleanField(default=False, max_length=10, verbose_name='Флаг'),
        ),
    ]
