# Generated by Django 4.2.2 on 2023-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0011_student_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='need_card',
            field=models.CharField(default='', max_length=100, verbose_name='Нужно ли положить карту'),
        ),
    ]
