# Generated by Django 4.2.2 on 2023-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0012_student_need_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Count', models.CharField(max_length=20, verbose_name='количество игроков')),
                ('player1', models.CharField(max_length=20, verbose_name='айди игрока 1')),
                ('player2', models.CharField(max_length=20, verbose_name='айди игрока 2')),
                ('player3', models.CharField(max_length=20, verbose_name='айди игрока 3')),
                ('player4', models.CharField(max_length=20, verbose_name='айди игрока 4')),
            ],
        ),
    ]
