# Generated by Django 4.2.2 on 2023-06-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0013_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lobby_id',
            field=models.CharField(default='None', max_length=20, verbose_name='номер лобби'),
        ),
    ]
