# Generated by Django 4.2.2 on 2023-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0015_student_game_index_alter_student_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='game_index',
            field=models.CharField(default='None', max_length=20, verbose_name='номер игры'),
        ),
    ]
