# Generated by Django 4.2.2 on 2023-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0016_alter_student_game_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
