# Generated by Django 4.2.2 on 2023-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0017_lobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Query_Count',
            field=models.CharField(default=None, max_length=20, verbose_name='количество запросов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='query1',
            field=models.CharField(default='None', max_length=20, verbose_name='айди игрока на запрос 1'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='query2',
            field=models.CharField(default='None', max_length=20, verbose_name='айди игрока на запрос 1'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='query3',
            field=models.CharField(default='None', max_length=20, verbose_name='айди игрока на запрос 1'),
        ),
    ]
